name: Publish to NPM Registry

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm adduser --auth-type=legacy --registry=https://nexus.mekomsolutions.net/repository/mks-npm/
        env:
          USERNAME: ${{ secrets.NPM_USERNAME }}
          PASSWORD: ${{ secrets.NPM_TOKEN }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
